server:
  port: 9000
spring:
  application:
    name: invoker1
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/,http://localhost:8762/eureka/