server:
  port: 9000
spring:
  application:
    name: invoker
  cloud:
    loadbalancer:
      retry: false
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#    registry-fetch-interval-seconds: 30
logging:
  level:
    com.netflix: debug