server:
  port: 8080
spring:
  application:
    name: gateway
zuul:
  routes:
    invoker1:
      url: http://47.101.48.26:9000
management:
  security:
    enabled: false
eureka:
  instance:
    hostname: eureka
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/,http://eureka:8762/eureka/
    registry-fetch-interval-seconds: 30
logging:
  level:
    com.netflix: debug