server:
  port: 8888
encrypt:
  key: Spark
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SparkZhou1994/SpringCloudDemo
          search-paths: config-repo
          username:
          password:
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/,http://eureka:8762/eureka/