server:
  port: 8762
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
spring:
  application:
    name: eureka2