server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/
    register-with-eureka: true
  instance:
    hostname: eureka2
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
spring:
  application:
    name: eureka