server:
  port: 8761
eureka:
  client:
    service-url:
      default-zone: http://eureka2:8762/eureka/
  instance:
    hostname: eureka1
  server:
#   enable-self-preservation: false
#    eviction-interval-timer-in-ms: 5000
spring:
  application:
    name: eureka