server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://eureka2:8762/eureka/
    register-with-eureka: false
  instance:
    hostname: eureka1
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
spring:
  application:
    name: eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SparkZhou1994/SpringCloudDemo/
management:
  security:
    enabled: false
