spring:
  application:
    name: provider
eureka:
  instance:
    hostname: eureka
#    leaseRenewalIntervalInSeconds: 5
#    lease-expiration-duration-in-seconds: 10
    metadata-map:
      editor: Spark
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/,http://eureka:8762/eureka/
server:
  port: 8080
logging:
  level:
    com.netflix: debug